<a href="https://colab.research.google.com/github/arturomolin/Tarea1/blob/main/Ejercicio_22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pregunta 22



In [ ]:
import numpy as np
from numpy import linalg as LA

def Transpuesta(Mat):
    """
    Calcula la transpuesta de una matriz cuadrada modificando la matriz original.

    Parámetros:
    -----------
    Mat : numpy.ndarray
        Matriz cuadrada de tamaño n x n que se transpondrá.
        La matriz se modificará in situ.

    Retorna:
    --------
    numpy.ndarray
        La matriz transpuesta. La matriz original también se modifica.

    Ejemplo:
    --------
    >>> Mat = np.array([[1, 2, 3],
    ...                [4, 5, 6],
    ...                [7, 8, 9]])
    >>> Transpuesta(Mat)
    array([[1, 4, 7],
           [2, 5, 8],
           [3, 6, 9]])
    """
    for ren in range(Mat.shape[0]):
        for col in range(Mat.shape[1]):
            if ren < col:
                # Intercambia los elementos para obtener la transpuesta
                Mat[ren, col], Mat[col, ren] = Mat[col, ren], Mat[ren, col]
    return Mat

def Cofactores(Mat):
    """
    Calcula la matriz de cofactores de una matriz cuadrada.

    Parámetros:
    -----------
    Mat : numpy.ndarray
        Matriz cuadrada de tamaño n x n para la cual se calcularán los cofactores.

    Retorna:
    --------
    numpy.ndarray
        Matriz de cofactores, donde cada elemento es el cofactor correspondiente
        de la matriz original.

    Ejemplo:
    --------
    >>> Mat = np.array([[1, 2],
    ...                [3, 4]])
    >>> Cofactores(Mat)
    array([[ 4., -3.],
           [-2.,  1.]])
    """
    # Crear una matriz de ceros del mismo tamaño que Mat para almacenar los cofactores
    Cofa = np.zeros_like(Mat, dtype=float)

    # Calcular el cofactor para cada elemento de la matriz
    for ren in range(Mat.shape[0]):
        for col in range(Mat.shape[1]):
            # Calcular el determinante de la submatriz (menor) y aplicar el signo
            Cofa[ren, col] = ((-1) ** (ren + col)) * Det(SubMat(Mat, ren, col))
    return Cofa

def SubMat(Mat, ren, col):
    """
    Crea una submatriz eliminando un renglón y una columna específicos de la matriz original.

    Parámetros:
    -----------
    Mat : numpy.ndarray
        Matriz original de la cual se obtendrá la submatriz.
    ren : int
        Índice del renglón que se eliminará de la matriz.
    col : int
        Índice de la columna que se eliminará de la matriz.

    Retorna:
    --------
    numpy.ndarray
        Submatriz resultante después de eliminar el renglón y la columna especificados.

    Ejemplo:
    --------
    >>> Mat = np.array([[1, 2, 3],
    ...                [4, 5, 6],
    ...                [7, 8, 9]])
    >>> SubMat(Mat, 1, 1)
    array([[1, 3],
           [7, 9]])
    """
    # Crear una copia de la matriz original para no modificarla
    M1 = np.copy(Mat)

    # Eliminar el renglón especificado
    M1 = np.delete(M1, ren, axis=0)

    # Eliminar la columna especificada
    M1 = np.delete(M1, col, axis=1)

    return M1

def Det(Mat):
    """
    Calcula el determinante de una matriz cuadrada de manera recursiva.

    Parámetros:
    -----------
    Mat : numpy.ndarray
        Matriz cuadrada de la cual se calculará el determinante.
        Debe ser de tamaño n x n, donde n >= 2.

    Retorna:
    --------
    float
        El determinante de la matriz.

    Ejemplo:
    --------
    >>> Mat = np.array([[1, 2],
    ...                [3, 4]])
    >>> Det(Mat)
    -2.0

    >>> Mat = np.array([[6, 1, 1],
    ...                [4, -2, 5],
    ...                [2, 8, 7]])
    >>> Det(Mat)
    -306.0
    """
    # Caso base: matriz 2x2
    if Mat.shape[0] == 2 and Mat.shape[1] == 2:
        return Mat[0][0] * Mat[1][1] - (Mat[0][1] * Mat[1][0])

    # Caso recursivo: matrices más grandes
    deter = 0.0
    for col in range(Mat.shape[0]):
        # Calcula el cofactor y suma al determinante
        deter += ((-1) ** col) * Mat[0][col] * Det(SubMat(Mat, 0, col))
    return deter

def Inv(Mat):
    """
    Calcula la inversa de una matriz cuadrada utilizando la matriz de cofactores.

    Parámetros:
    -----------
    Mat : numpy.ndarray
        Matriz cuadrada de tamaño n x n que se invertirá.
        Debe ser una matriz no singular (su determinante debe ser distinto de cero).

    Retorna:
    --------
    numpy.ndarray
        La matriz inversa de la matriz original.

    Ejemplo:
    --------
    >>> Mat = np.array([[4, 7],
    ...                [2, 6]])
    >>> Inv(Mat)
    array([[ 0.6, -0.7],
           [-0.2,  0.4]])
    """
    # Calcular el determinante de la matriz
    deter = Det(Mat)

    # Verificar si la matriz es singular (determinante = 0)
    if deter == 0:
        raise ValueError("La matriz es singular y no tiene inversa.")

    # Calcular la matriz de cofactores
    Cofac = Cofactores(Mat)

    # Transponer la matriz de cofactores para obtener la matriz adjunta
    Cofac = Transpuesta(Cofac)

    # Calcular la inversa multiplicando la adjunta por 1/determinante
    Inversa = (1 / deter) * Cofac

    return Inversa
# @title Formulario
def SustitucionDelante(Mat, b):
    """
    Realiza la sustitución hacia adelante para resolver un sistema de ecuaciones lineales
    representado por una matriz triangular inferior.

    Parámetros:
    -----------
    Mat : numpy.ndarray
        Una matriz triangular inferior de tamaño n x n.
    b : numpy.ndarray
        Un vector de términos independientes de tamaño n.

    Retorna:
    --------
    x : numpy.ndarray
        Un vector solución de tamaño n que satisface la ecuación Mat @ x = b.

    Descripción:
    ------------
    Esta función resuelve un sistema de ecuaciones lineales de la forma Mat @ x = b,
    donde Mat es una matriz triangular inferior. Utiliza el método de sustitución hacia adelante,
    comenzando desde la primera fila de la matriz y avanzando hacia la última.

    Ejemplo:
    --------
    >>> Mat = np.array([[1, 0, 0],
    ...                 [2, 3, 0],
    ...                 [4, 5, 6]])
    >>> b = np.array([1, 8, 32])
    >>> SustitucionDelante(Mat, b)
    array([1., 2., 3.])
    """
    n = Mat.shape[0]
    x = np.zeros(n)

    for i in range(n):
        SumCum = 0.0
        for j in range(i):
            SumCum += Mat[i, j] * x[j]
        x[i] = (b[i] - SumCum) / Mat[i, i]

    return x

def SustitucionAtras(Mat, b):
    """
    Realiza la sustitución hacia atrás para resolver un sistema de ecuaciones lineales
    representado por una matriz triangular superior.

    Parámetros:
    -----------
    Mat : numpy.ndarray
        Una matriz triangular superior de tamaño n x n.
    b : numpy.ndarray
        Un vector de términos independientes de tamaño n.

    Retorna:
    --------
    x : numpy.ndarray
        Un vector solución de tamaño n que satisface la ecuación Mat @ x = b.

    Descripción:
    ------------
    Esta función resuelve un sistema de ecuaciones lineales de la forma Mat @ x = b,
    donde Mat es una matriz triangular superior. Utiliza el método de sustitución hacia atrás,
    comenzando desde la última fila de la matriz y avanzando hacia la primera.

    Ejemplo:
    --------
    >>> Mat = np.array([[3, 2, 1],
    ...                 [0, 2, 1],
    ...                 [0, 0, 1]])
    >>> b = np.array([6, 4, 1])
    >>> SustitucionAtras(Mat, b)
    array([1., 1., 1.])
    """
    n = Mat.shape[0]
    x = np.zeros(n)

    for i in range(n-1, -1, -1):
        SumCum = 0.0
        for j in range(i+1, n):
            SumCum += Mat[i, j] * x[j]
        x[i] = (b[i] - SumCum) / Mat[i, i]

    return x

def LU(A):
  U=np.copy(A)
  L=np.eye(A.shape[0])

  for i in range(A.shape[0]):
    Li=np.eye(A.shape[0])
    for j in range(i+1,A.shape[0]):
      Li[j,i]=-U[j,i]/U[i,i]
      L[j,i]=U[j,i]/U[i,i]
    U=Li@U
  return L,U

def SolverLU(A,b):
  L,U=LU(A)
  # El sistema que se resuelve es Ly=b
  y=SustitucionDelante(L, b)
  # El sistema que se resuelve es Ux=y
  x=SustitucionAtras(U, y)

  return x

def Permutaciones(A,b):
  U=np.copy(A)
  x=np.copy(b)
  P=np.eye(A.shape[0])

  for j in range(A.shape[0]):
    k=np.argmax(np.abs(A[j:,j]))+j
    U[[j,k]]=U[[k,j]]
    P[[j,k]]=P[[k,j]]
    x[[j,k]]=x[[k,j]]

  return P,U,x


def Solver_LU_Pivot_Partial(A,b):
    P,Ap,bp=Permutaciones(A,b)
    x=SolverLU(Ap,bp)

    return x

def condicion_matriz_norma1(A):
    # Calcula la inversa usando tu función Inv (basada en cofactores)
    A_inv = Inv(A)

    # Calcula la norma 1 de A y de su inversa
    norma_A = np.linalg.norm(A, ord=1)
    norma_A_inv = np.linalg.norm(A_inv, ord=1)

    # Regresa el número de condición
    return norma_A * norma_A_inv


##(a) ¿Qué sucede cuando se usa Eliminación Gaussina con pivoteo parcial?.

Primero insertamos la matriz inicial junto con las matrices prueba de las soluciones, esto para que corran nuestras funciones

In [ ]:
A=np.array([[1.,0.,0.,0.,1.],
            [-1.,1.,0.,0.,1.],
            [-1.,-1.,1.,0.,1.],
            [-1.,-1.,-1.,1.,1.],
            [-1.,-1.,-1.,-1.,1.]])

b=np.array([1.,1.,1.,1.,1.])
c=np.array([2.,2.,2.,2.,2.])
d=np.array([3.,3.,3.,3.,3.])
e=np.array([4.,4.,4.,4.,4.])
f=np.array([5.,5.,5.,5.,5.])

Ahora, hacemos el proceso de pivoteo parcial para ver como se comporta la matriz A al final

In [ ]:
P, U, x = Permutaciones(A, b)

L, U = LU(U)
U

array([[ 1.,  0.,  0.,  0.,  1.],
       [ 0.,  1.,  0.,  0.,  2.],
       [ 0.,  0.,  1.,  0.,  4.],
       [ 0.,  0.,  0.,  1.,  8.],
       [ 0.,  0.,  0.,  0., 16.]])

Podemos observar un comportamiento peculiar en la matriz, ya que tenemos casi una matriz identidad, solo que con la última columna con un 2^n.

##(b) Usar Eliminación Gaussina con pivoteo parcial para resolver sistemas de varios tamaños (al menos 5) con vectores b elegidos por cualquier criterio. Describir como se comporta la condición de la matriz.

In [ ]:
solb = Solver_LU_Pivot_Partial(A,b)
solc = Solver_LU_Pivot_Partial(A,c)
sold = Solver_LU_Pivot_Partial(A,d)
sole = Solver_LU_Pivot_Partial(A,e)
solf = Solver_LU_Pivot_Partial(A,f)
print(f"La solución del sistema Ax=b es: {solb}")
print(f"La solución del sistema Ax=c es: {solc}")
print(f"La solución del sistema Ax=d es: {sold}")
print(f"La solución del sistema Ax=e es: {sole}")
print(f"La solución del sistema Ax=f es: {solf}")

La solución del sistema Ax=b es: [0. 0. 0. 0. 1.]
La solución del sistema Ax=c es: [0. 0. 0. 0. 2.]
La solución del sistema Ax=d es: [0. 0. 0. 0. 3.]
La solución del sistema Ax=e es: [0. 0. 0. 0. 4.]
La solución del sistema Ax=f es: [0. 0. 0. 0. 5.]


In [ ]:
condicion = np.linalg.cond(A, p=1)
condicion

np.float64(5.0)

In [ ]:
cond = condicion_matriz_norma1(A)
cond

np.float64(5.0)

Tenemos que la condicion de la matriz con norma 1 es 5, por lo que es relativamente baja, por lo tanto la matriz esta bien condicionada

# (c) Escribir una rutina que factorice la matriz (LU) con pivoteo total.

Creamos 2 funciones, una para las permutaciones y otra para la solución:

In [ ]:
def Permutacionestot(A, b):
    n = A.shape[0]  # Tamaño de la matriz (n x n)
    U = np.copy(A)  # Copia de la matriz A para no modificarla directamente
    x = np.copy(b)  # Copia del vector b
    P = np.eye(n)   # Matriz de permutación de filas (inicialmente identidad)
    Q = np.eye(n)   # Matriz de permutación de columnas (inicialmente identidad)

    for k in range(n - 1):
        # --- PASO 1: Encontrar el pivote máximo en la submatriz U[k:, k:] ---
        # np.abs(U[k:, k:]): Valores absolutos de la submatriz desde (k,k) hasta el final
        # np.argmax(...): Índice lineal del elemento con mayor valor absoluto (en arreglo aplanado)
        # np.unravel_index(...): Convierte el índice lineal a coordenadas (fila, columna) en la submatriz
        max_row, max_col = np.unravel_index(np.argmax(np.abs(U[k:, k:])), (n - k, n - k))

        # Ajustar índices para referenciar la posición en la matriz original U (no solo la submatriz)
        max_row += k
        max_col += k

        # --- PASO 2: Intercambiar filas para llevar el pivote a la posición (k,k) ---
        # Intercambia filas en U
        U[[k, max_row]] = U[[max_row, k]]
        # Intercambia filas en la matriz de permutación P
        P[[k, max_row]] = P[[max_row, k]]
        # Intercambia elementos en el vector x
        x[[k, max_row]] = x[[max_row, k]]

        # --- PASO 3: Intercambiar columnas para optimizar la factorización ---
        # Intercambia columnas en U
        U[:, [k, max_col]] = U[:, [max_col, k]]
        # Intercambia columnas en la matriz de permutación Q
        Q[:, [k, max_col]] = Q[:, [max_col, k]]

    return P, Q, U, x  # Devuelve: Matrices de permutación, matriz triangular, y vector modificado

def LU_tot(A,b):
    P,Q,A_g,b_g=Permutacionestot(A,b)
    x=LU(A_g)

    return x

In [ ]:
L, U = LU_tot(A, b)
print("Matriz L:")
print(L)
print("\nMatriz U:")
print(U)

Matriz L:
[[ 1.  0.  0.  0.  0.]
 [-1.  1.  0.  0.  0.]
 [-1. -1.  1.  0.  0.]
 [-1. -1. -1.  1.  0.]
 [-1. -1. -1. -1.  1.]]

Matriz U:
[[ 1.  0.  0.  0.  1.]
 [ 0.  1.  0.  0.  2.]
 [ 0.  0.  1.  0.  4.]
 [ 0.  0.  0.  1.  8.]
 [ 0.  0.  0.  0. 16.]]
