<a href="https://colab.research.google.com/github/arturomolin/Tarea1/blob/main/problema_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#jorge israel molina valle
import numpy as np  # se importo numpy para trabajar con matrices

def cholesky_LLT(A):
    #definimos la factorizacion de Cholesky clasica: A = LLᵀ inciso a
    n = A.shape[0]  # se definen los numeros de filas y columnas pues la matriz es cuadrada
    L = np.zeros_like(A)  # se crea una matriz L del mismo tamaño que A o la original llena de ceros

    for i in range(n):  # se recorrern las filas
        for j in range(i + 1):  # se rcorren las columnas hasta la diagonal
            sum_k = np.dot(L[i, :j], L[j, :j])  # se suman los productos L[i,k] * L[j,k] desde k=0 hasta j-1
            if i == j:
                val = A[i, i] - sum_k  # para la diagonal calculamos el valor restante
                if val <= 0:
                    raise ValueError("La matriz no es positiva lo cual es un error.")
                L[i, j] = np.sqrt(val)  # se calcula la raíz cuadrada para la diagonal
            else:
                L[i, j] = (A[i, j] - sum_k) / L[j, j]
    return L  # se devuelve la matriz L

def cholesky_LDLT(A):
    #Factorización de Cholesky con pivote diagonal: A = L D Lᵀ inciso b
    n = A.shape[0]  # se define el numero de filas y columnas
    L = np.identity(n)  # se crea una matriz identidad para L
    D = np.zeros((n, n))  # se crea una matriz diagonal vacía

    for j in range(n):  # se recorren las columnas
        # Calculamos D[j, j]
        sum_LDL = sum(D[k, k] * L[j, k] ** 2 for k in range(j))  # se hace una suma parcial
        D[j, j] = A[j, j] - sum_LDL
        if D[j, j] <= 0:
            raise ValueError("La matriz no es  positiva lo cual es un error.")
        # se calculan los elementos debajo de la diagonal en la columna j
        for i in range(j + 1, n):
            sum_LDL = sum(D[k, k] * L[i, k] * L[j, k] for k in range(j))  # se hace una suma parcial
            L[i, j] = (A[i, j] - sum_LDL) / D[j, j]
    return L, D  # se devuelve la matriz L y D

def leer_matriz_manual():
    #ya habia hecho un programa similar para otra materia asi que permiti
    #que se ingresaran las matrices desde el teclado
    while True:
        try:
            n = int(input("Ingresa el tamaño n de la matriz cuadrada nxn: "))  # se pide el tamaño
            if n <= 0:
                print("El tamaño debe ser mayor que 0.")
                continue
            break
        except ValueError:
            print("Por favor, ingrese un numero entero mayor que cero.")

    A = np.zeros((n, n))  # se crea la matriz de ceros nxn

    print("\nIngresa los elementos de la matriz (por filas):")
    for i in range(n): #se definen los rangos de i y j para pedir los valores
        for j in range(n):
            while True:
                try:
                    A[i, j] = float(input(f"A[{i+1}][{j+1}]: "))  # se pide cada valor
                    break
                except ValueError:
                    print("Entrada invalida. Intentalo de nuevo.")#se manda mensaje de error
    return A  # se devuelve la matriz

def seleccionar_matriz():
    #aqui se escribieron las matrices del problema
    #permitiendo elegir entre las matrices A, B, C, D o una que se ingrese manualmente
    matrices = {
        'A': np.array([[2, -1, 0],
                       [-1, 2, -1],
                       [0, -1, 2]]),
        'B': np.array([[4, 1, 1, 1],
                       [1, 3, -1, 1],
                       [1, -1, 2, 0],
                       [1, 1, 0, 2]]),
        'C': np.array([[4, 1, -1, 0],
                       [1, 3, -1, 0],
                       [-1, -1, 5, 2],
                       [0, 0, 2, 4]]),
        'D': np.array([[6, 2, 1, -1],
                       [2, 4, 1, 0],
                       [1, 1, 4, -1],
                       [-1, 0, -1, 3]])
    }

    print("\nSelecciona la matriz a factorizar:")
    print("A. Matriz A (3x3)")
    print("B. Matriz B (4x4)")
    print("C. Matriz C (4x4)")
    print("D. Matriz D (4x4)")
    print("M. Ingresar manualmente una matriz cuadrada")#las matrices descritas aqui son las del problema 26
    while True:
        opcion = input("Ingresa A, B, C, D o M: ").upper() #se selecciona la matriz a trabajar
        if opcion in matrices:
            return matrices[opcion], opcion  # se devuleve la  matriz elegida
        elif opcion == 'M':
            return leer_matriz_manual(), 'M'  # se devulve la matriz manual
        print("Opción inválida. Intentalo nuevamente.")

def menu_factorizacion():
    #se da la opcion para elegir el tipo de factorización ya se la del inciso a o b
    print("\nSelecciona el tipo de factorización:")
    print("1. Cholesky Clásica (A = LLᵀ)")
    print("2. Cholesky con pivote diagonal (A = L D Lᵀ)")
    while True:
        opcion = input("Selecciona 1 o 2: ")
        if opcion in ['1', '2']:
            return opcion
        print("Opción inválida. Intentalo nuevamente.")

if __name__ == "__main__":
    # se selecciona la matriz
    A, nombre = seleccionar_matriz()

    print(f"\nMatriz seleccionada ({nombre}):")
    print(A)

    # s valida que la matriz sea cuadrada
    if A.shape[0] != A.shape[1]:
        print("\nLa matriz no es cuadrada por ende no se puede aplicar la factorización de Cholesky.")
    # Validamos que sea simétrica
    elif not np.allclose(A, A.T):
        print("\nLa matriz no es simétrica por ende no se puede aplicar la factorización de Cholesky.")
    else:
        # pedimos el tipo de factorizacion
        opcion = menu_factorizacion()
        try:
            if opcion == '1':
                print("\n--- Factorizacion A = LLᵀ ---")
                L = cholesky_LLT(A)
                print("L =")
                print(L)
                print("\n A = LLᵀ")
                print(L @ L.T)
            else:
                print("\n--- Factorizacion A = L D Lᵀ ---")
                L_hat, D_hat = cholesky_LDLT(A)
                print("L =")
                print(L_hat)
                print("D =")
                print(D_hat)
                print("\n A = L  D Lᵀ")
                print(L_hat @ D_hat @ L_hat.T)
        except Exception as e:
            print("Error durante la factorizacion:", e)


Selecciona la matriz a factorizar:
A. Matriz A (3x3)
B. Matriz B (4x4)
C. Matriz C (4x4)
D. Matriz D (4x4)
M. Ingresar manualmente una matriz cuadrada
Ingresa A, B, C, D o M: a

Matriz seleccionada (A):
[[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]

Selecciona el tipo de factorización:
1. Cholesky Clásica (A = LLᵀ)
2. Cholesky con pivote diagonal (A = L D Lᵀ)
Selecciona 1 o 2: 1

--- Factorizacion A = LLᵀ ---
L =
[[ 1  0  0]
 [-1  1  0]
 [ 0 -1  1]]

 A = LLᵀ
[[ 1 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]
