<a href="https://colab.research.google.com/github/arturomolin/Tarea1/blob/main/Cramer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ejercicio 2: Metodo de cramer
Primero importamos las funciones que vamos a usar (desde la paquetería elaborada en clase)


In [ ]:
# @title Funciones creadas en clase
import numpy as np  # Importamos la librería NumPy para trabajar con matrices y álgebra lineal

def SubMat(Mat, ren, col):
    """
    Crea una submatriz eliminando un renglón y una columna específicos de la matriz original.

    Parámetros:
    -----------
    Mat : numpy.ndarray
        Matriz original de la cual se obtendrá la submatriz.
    ren : int
        Índice del renglón que se eliminará de la matriz.
    col : int
        Índice de la columna que se eliminará de la matriz.

    Retorna:
    --------
    numpy.ndarray
        Submatriz resultante después de eliminar el renglón y la columna especificados.

    Ejemplo:
    --------
    >>> Mat = np.array([[1, 2, 3],
    ...                [4, 5, 6],
    ...                [7, 8, 9]])
    >>> SubMat(Mat, 1, 1)
    array([[1, 3],
           [7, 9]])
    """
    # Crear una copia de la matriz original para no modificarla
    M1 = np.copy(Mat)

    # Eliminar el renglón especificado
    M1 = np.delete(M1, ren, axis=0)

    # Eliminar la columna especificada
    M1 = np.delete(M1, col, axis=1)

    return M1
def Det(Mat): # Usamos lo visto en clase
    """
    Calcula el determinante de una matriz cuadrada de manera recursiva.

    Parámetros:
    -----------
    Mat : numpy.ndarray
        Matriz cuadrada de la cual se calculará el determinante.
        Debe ser de tamaño n x n, donde n >= 2.

    Retorna:
    --------
    float
        El determinante de la matriz.

    Ejemplo:
    --------
    >>> Mat = np.array([[1, 2],
    ...                [3, 4]])
    >>> Det(Mat)
    -2.0

    >>> Mat = np.array([[6, 1, 1],
    ...                [4, -2, 5],
    ...                [2, 8, 7]])
    >>> Det(Mat)
    -306.0
    """
    # Caso base: matriz 2x2
    if Mat.shape[0] == 2 and Mat.shape[1] == 2:
        return Mat[0][0] * Mat[1][1] - (Mat[0][1] * Mat[1][0])

    # Caso recursivo: matrices más grandes
    deter = 0.0
    for col in range(Mat.shape[0]):
        # Calcula el cofactor y suma al determinante
        deter += ((-1) ** col) * Mat[0][col] * Det(SubMat(Mat, 0, col))
    return deter

def Transpuesta(Mat):
    """
    Calcula la transpuesta de una matriz cuadrada modificando la matriz original.

    Parámetros:
    -----------
    Mat : numpy.ndarray
        Matriz cuadrada de tamaño n x n que se transpondrá.
        La matriz se modificará in situ.

    Retorna:
    --------
    numpy.ndarray
        La matriz transpuesta. La matriz original también se modifica.

    Ejemplo:
    --------
    >>> Mat = np.array([[1, 2, 3],
    ...                [4, 5, 6],
    ...                [7, 8, 9]])
    >>> Transpuesta(Mat)
    array([[1, 4, 7],
           [2, 5, 8],
           [3, 6, 9]])
    """
    for ren in range(Mat.shape[0]):
        for col in range(Mat.shape[1]):
            if ren < col:
                # Intercambia los elementos para obtener la transpuesta
                Mat[ren, col], Mat[col, ren] = Mat[col, ren], Mat[ren, col]
    return Mat
def Cofactores(Mat):
    """
    Calcula la matriz de cofactores de una matriz cuadrada.

    Parámetros:
    -----------
    Mat : numpy.ndarray
        Matriz cuadrada de tamaño n x n para la cual se calcularán los cofactores.

    Retorna:
    --------
    numpy.ndarray
        Matriz de cofactores, donde cada elemento es el cofactor correspondiente
        de la matriz original.

    Ejemplo:
    --------
    >>> Mat = np.array([[1, 2],
    ...                [3, 4]])
    >>> Cofactores(Mat)
    array([[ 4., -3.],
           [-2.,  1.]])
    """
    # Crear una matriz de ceros del mismo tamaño que Mat para almacenar los cofactores
    Cofa = np.zeros_like(Mat, dtype=float)

    # Calcular el cofactor para cada elemento de la matriz
    for ren in range(Mat.shape[0]):
        for col in range(Mat.shape[1]):
            # Calcular el determinante de la submatriz (menor) y aplicar el signo
            Cofa[ren, col] = ((-1) ** (ren + col)) * Det(SubMat(Mat, ren, col))
    return Cofa

def Inv(Mat):
    """
    Calcula la inversa de una matriz cuadrada utilizando la matriz de cofactores.

    Parámetros:
    -----------
    Mat : numpy.ndarray
        Matriz cuadrada de tamaño n x n que se invertirá.
        Debe ser una matriz no singular (su determinante debe ser distinto de cero).

    Retorna:
    --------
    numpy.ndarray
        La matriz inversa de la matriz original.

    Ejemplo:
    --------
    >>> Mat = np.array([[4, 7],
    ...                [2, 6]])
    >>> Inv(Mat)
    array([[ 0.6, -0.7],
           [-0.2,  0.4]])
    """
    # Calcular el determinante de la matriz
    deter = Det(Mat)

    # Verificar si la matriz es singular (determinante = 0)
    if deter == 0:
        raise ValueError("La matriz es singular y no tiene inversa.")

    # Calcular la matriz de cofactores
    Cofac = Cofactores(Mat)

    # Transponer la matriz de cofactores para obtener la matriz adjunta
    Cofac = Transpuesta(Cofac)

    # Calcular la inversa multiplicando la adjunta por 1/determinante
    Inversa = (1 / deter) * Cofac

    return Inversa

def SolveInv(Mat, vec):
    """
    Resuelve un sistema de ecuaciones lineales utilizando la matriz inversa.

    Parámetros:
    -----------
    Mat : numpy.ndarray
        Matriz cuadrada de coeficientes del sistema de ecuaciones.
        Debe ser una matriz no singular (su determinante debe ser distinto de cero).

    vec : numpy.ndarray
        Vector de términos independientes.
        Su tamaño debe coincidir con el número de filas de la matriz `Mat`.

    Retorna:
    --------
    numpy.ndarray
        Vector solución del sistema de ecuaciones `Mat @ x = vec`.

    Excepciones:
    ------------
    ValueError
        Se lanza un error si la matriz `Mat` no es invertible.

    Ejemplo:
    --------
    >>> Mat = np.array([[2, 1],
    ...                 [5, 3]])
    >>> vec = np.array([4, 10])
    >>> SolveInv(Mat, vec)
    array([2., 0.])

    """
    # Calcular la inversa de la matriz
    InvMat = Inv(Mat)

    # Multiplicar la inversa por el vector de términos independientes
    Solucion = InvMat @ vec

    return Solucion

Ahora, creamos la función del metodo de cramer

In [ ]:
def metodo_cramer(A, b):
    """
    Resuelve un sistema de ecuaciones usando el metodo de Cramer.

    Este método solo funciona cuando el determinante de la matriz de coeficientes no es cero

    Parámetros:
    -----------
    A : numpy.ndarray
        Matriz de coeficientes (debe ser cuadrada y no singular).
    b : numpy.ndarray
        Vector de términos independientes.

    Retorna:
    numpy.ndarray
        Vector solución del sistema de ecuaciones.
    """
    det_A = Det(A)  # Usamos la función Det vista en clase para calcular el determinante

    if det_A == 0:
        raise ValueError("El sistema no tiene solución única (determinante cero).")

    n = A.shape[0] # Esto es para saber cuando termina el ciclo For
    solucion = np.zeros(n)  # Creamos un array para almacenar las soluciones

    for i in range(n):
        Ai = A.copy() # Se crea una copia en cada iteración porque en cada iteración se cambia la matriz, también es para no crear confuciones
        Ai[:, i] = b  # Sustituir la columna i por el vector de términos independientes
        solucion[i] = Det(Ai) / det_A  # Aplicamos la regla de Cramer

    return solucion

Ahora comparamos con la función SolveInv vista en clase

In [ ]:
A=np.array([[2,3,-4],
            [0,-4,2],
            [1,-1,5]])
b=np.array([1.0,1.0,1.0])

solucion = metodo_cramer(A, b)
print("Solución del sistema con metodo de cramer:")
print(solucion)
print("Solución del sistema con la función SolveInv:")
Sol=SolveInv(A,b)
print(Sol)


Solución del sistema con metodo de cramer:
[ 0.84782609 -0.26086957 -0.02173913]
Solución del sistema con la función SolveInv:
[ 0.84782609 -0.26086957 -0.02173913]


Lo hacemos con una matriz más grande y tomamos el tiempo de ejeción

In [ ]:
import time
A= np.array([[3, 1, -2, 4, 2, -1, 5],
               [1, 5, 3, -2, 6, 4, -3],
               [-2, 3, 6, 1, -5, 2, 3],
               [4, -2, 1, 7, 3, -6, 2],
               [2, 6, -5, 3, 8, 1, -4],
               [-1, 4, 2, -6, 1, 5, 3],
               [5, -3, 3, 2, -4, 6, 7]])
b=np.array([2, -1, 3, 4, -2, 5, 1])

# Medir tiempo de ejecución para cada método con la matriz 5x5
start_cramer = time.time()
sol_cramer_5 = metodo_cramer(A, b)
end_cramer = time.time()
print("Solución con Cramer (5x5):", sol_cramer_5)
print("Tiempo de ejecución de Cramer (5x5):", end_cramer - start_cramer, "segundos")

start_inv = time.time()
sol_inv_5 = SolveInv(A, b)
end_inv = time.time()
print("Solución con Matriz Inversa (5x5):", sol_inv_5)
print("Tiempo de ejecución de Inversa (5x5):", end_inv - start_inv, "segundos")


Solución con Cramer (5x5): [ 8.00271944  4.6720426  -0.16343103 -4.01495694 -4.44987914 -4.24463665
 -1.25842272]
Tiempo de ejecución de Cramer (5x5): 0.27889084815979004 segundos
Solución con Matriz Inversa (5x5): [ 8.00271944  4.6720426  -0.16343103 -4.01495694 -4.44987914 -4.24463665
 -1.25842272]
Tiempo de ejecución de Inversa (5x5): 0.3103201389312744 segundos


Ahora con una matriz mucho más grande, para que podamos observar bien el tiempo de ejecución

In [ ]:
A= np.array([[3, 1, -2, 4, 2, -1, 5, 2, -3, 1],
                [1, 5, 3, -2, 6, 4, -3, 3, -1, 2],
                [-2, 3, 6, 1, -5, 2, 3, -4, 5, -2],
                [4, -2, 1, 7, 3, -6, 2, 1, -5, 3],
                [2, 6, -5, 3, 8, 1, -4, 2, 6, -1],
                [-1, 4, 2, -6, 1, 5, 3, -2, 4, 7],
                [5, -3, 3, 2, -4, 6, 7, -1, 3, 2],
                [2, -1, 4, 3, -6, 5, 1, 7, -2, 6],
                [-3, 2, 1, -5, 4, 3, -6, 2, 8, 1],
                [1, -2, 5, 3, -4, 6, 7, -1, 2, 9]])
b=np.array([1, -2, 3, 4, -1, 5, 2, -3, 6, 7])

# Medir tiempo de ejecución para cada método con la matriz 5x5
start_cramer = time.time()
sol_cramer_5 = metodo_cramer(A, b)
end_cramer = time.time()
print("Solución con Cramer (5x5):", sol_cramer_5)
print("Tiempo de ejecución de Cramer (5x5):", end_cramer - start_cramer, "segundos")

start_inv = time.time()
sol_inv_5 = SolveInv(A, b)
end_inv = time.time()
print("Solución con Matriz Inversa (5x5):", sol_inv_5)
print("Tiempo de ejecución de Inversa (5x5):", end_inv - start_inv, "segundos")

Solución con Cramer (5x5): [-0.77378794 -0.67533005  0.66118976 -0.08184638  0.81834853 -0.76044848
  0.97322565  0.44953931  0.94754497  0.32674144]
Tiempo de ejecución de Cramer (5x5): 306.91538882255554 segundos
Solución con Matriz Inversa (5x5): [-0.77378794 -0.67533005  0.66118976 -0.08184638  0.81834853 -0.76044848
  0.97322565  0.44953931  0.94754497  0.32674144]
Tiempo de ejecución de Inversa (5x5): 305.0945019721985 segundos
