<a href="https://colab.research.google.com/github/arturomolin/Tarea1/blob/main/ejercicio21.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Alumno: Molina Valle Arturo.
# Voy a ocupar tal cual algunas definciones y comandos que se ocuparon en clase, para despues simplemente juntarlos aquí.

import numpy as np
from numpy import linalg as LA

#A continuación vamos a definir nuestras funciones, las cuales sacamos de los apuntes en git-hub
#-----Funciones-----
def SustitucionDelante(Mat, b):
    n = Mat.shape[0]
    x = np.zeros(n)
    for i in range(n):
        x[i] = (b[i] - np.dot(Mat[i, :i], x[:i])) / Mat[i, i]
    return x

def SustitucionAtras(Mat, b):
    n = Mat.shape[0]
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (b[i] - np.dot(Mat[i, i+1:], x[i+1:])) / Mat[i, i]
    return x

def LU(A):
    U = np.copy(A)
    L = np.eye(A.shape[0])
    for i in range(A.shape[0]):
        for j in range(i+1, A.shape[0]):
            L[j, i] = U[j, i] / U[i, i]
            U[j] = U[j] - L[j, i] * U[i]
    return L, U

def SolverLU(A, b):
    L, U = LU(A)
    y = SustitucionDelante(L, b)
    x = SustitucionAtras(U, y)
    return x

def PermutacionesParcial(A, b):
    U = np.copy(A)
    x = np.copy(b)
    P = np.eye(A.shape[0])
    for j in range(A.shape[0]):
        k = np.argmax(np.abs(U[j:, j])) + j
        U[[j, k]] = U[[k, j]]
        P[[j, k]] = P[[k, j]]
        x[[j, k]] = x[[k, j]]
    return P, U, x

def Solver_LU_Pivot_Partial(A, b):
    P, A_pivot, b_pivot = PermutacionesParcial(A, b)
    return SolverLU(A_pivot, b_pivot)

def PermutacionesTotal(A, b):
    n = A.shape[0]
    U = np.copy(A)
    x = np.copy(b)
    P = np.eye(n)
    Q = np.eye(n)
    for k in range(n - 1):
        max_row, max_col = np.unravel_index(np.argmax(np.abs(U[k:, k:])), (n - k, n - k))
        max_row += k
        max_col += k
        U[[k, max_row]] = U[[max_row, k]]
        P[[k, max_row]] = P[[max_row, k]]
        x[[k, max_row]] = x[[max_row, k]]
        U[:, [k, max_col]] = U[:, [max_col, k]]
        Q[:, [k, max_col]] = Q[:, [max_col, k]]
    return P, Q, U, x

def Solver_LU_Pivot_Total(A, b):
    P, Q, A_g, b_g = PermutacionesTotal(A, b)
    x = SolverLU(A_g, b_g)
    return Q @ x


#Ahora, como el problema nos pide calcular cada sistema con cada una de las rutinas, vamos a hacer los comandos, para meter la matriz A y el vector b.
#NOTA: Me base tal cual y como salen los codigos en git-hub, solo que fui cambiando las dimensiones tanto de A como de b.
#------Sistemas------
sistemas = {
    "a": (
        np.array([[4, -1, 3], [-8, 4, -7], [12, 1, 8]], dtype=float),
        np.array([-8, 19, -19], dtype=float)
    ),
    "b": (
        np.array([
            [1, 4, -2, 1],
            [-2, -4, -3, 1],
            [1, 16, -17, 9],
            [2, 4, -9, -3]
        ], dtype=float),
        np.array([3.5, -2.5, 15, 10.5], dtype=float)
    ),
    "c": (
        np.array([
            [4, 5, -1, 2, 3],
            [12, 13, 0, 10, 3],
            [-8, -8, 5, -11, 4],
            [16, 18, -7, 20, 4],
            [-4, -9, 31, -31, -1]
        ], dtype=float),
        np.array([34, 93, -33, 131, -58], dtype=float)
    )
}

# Ahora solo falta imprimir los resultados y terminar con el procedimiento.
#-----Resultados-----
for etiqueta, (A, b) in sistemas.items():
    print(f"\n--- Sistema {etiqueta.upper()} ---")

    print("Solución LU directa:")
    try:
        print(SolverLU(A, b))
    except Exception as e:
        print("Error en LU directa:", e)

    print("Solución LU con pivoteo parcial:")
    try:
        print(Solver_LU_Pivot_Partial(A, b))
    except Exception as e:
        print("Error en pivoteo parcial:", e)
    print("Solución LU con pivoteo total:")
    try:
        print(Solver_LU_Pivot_Total(A, b))
    except Exception as e:
        print("Error en pivoteo total:", e)

    print("Solución analítica (np.linalg.solve):")
    try:
        print(LA.solve(A, b))
    except Exception as e:
        print("Error en solución analítica:", e)




--- Sistema A ---
Solución LU directa:
[-1.  1. -1.]
Solución LU con pivoteo parcial:
[-1.  1. -1.]
Solución LU con pivoteo total:
[-1.  1. -1.]
Solución analítica (np.linalg.solve):
[-1.  1. -1.]

--- Sistema B ---
Solución LU directa:
[-0.5  1.  -0.5 -1. ]
Solución LU con pivoteo parcial:
[-0.5  1.  -0.5 -1. ]
Solución LU con pivoteo total:
[-0.5  1.  -0.5 -1. ]
Solución analítica (np.linalg.solve):
[-0.5  1.  -0.5 -1. ]

--- Sistema C ---
Solución LU directa:
[1. 2. 3. 4. 5.]
Solución LU con pivoteo parcial:
[1. 2. 3. 4. 5.]
Solución LU con pivoteo total:
[1. 2. 3. 4. 5.]
Solución analítica (np.linalg.solve):
[1. 2. 3. 4. 5.]
