<a href="https://colab.research.google.com/github/arturomolin/Tarea1/blob/main/ejercicio24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Alumno: Molina Valle Arturo.
# De igual forma que con mi ejercicio 21, voy a ocupar tal cual algunas definciones y comandos que se ocuparon en clase, para despues simplemente juntarlos aquí.
import numpy as np
from numpy import linalg as LA

#Definimos las funciones, las cuales sacamos el programa de Cholesky y de factorización LU de git-hub
#-----Funciones-----
def SustDelante(L, b):
    x = np.zeros_like(b)
    n = L.shape[0]
    for i in range(n):
        sum = 0.0
        for j in range(i):
            sum += L[i, j] * x[j]
        x[i] = (b[i] - sum) / L[i, i]
    return x

def SustAtras(U, y):
    x = np.zeros_like(y)
    n = U.shape[0]
    x[n - 1] = y[n - 1] / U[n - 1, n - 1]
    for i in range(n - 2, -1, -1):
        sum = 0.0
        for j in range(i + 1, n):
            sum += U[i, j] * x[j]
        x[i] = (y[i] - sum) / U[i, i]
    return x

def LU(A):
    n = A.shape[0]
    L = np.eye(n)
    U = np.copy(A)

    for j in range(n - 1):
        for i in range(j + 1, n):
            mult = U[i, j] / U[j, j]
            U[i, j:] -= mult * U[j, j:]
            L[i, j] = mult

    return L, U

def SolveLU(A, b):
    L, U = LU(A)
    y = SustDelante(L, b)
    x = SustAtras(U, y)
    return x

# A continuación vamos a definir lo que queremos calcular, es decir todo lo que ocuparemos en los incisos.
#-----Definiciones-----

      # Este paso es importante porque aqui tuve que notar como era el comportamiento de la matriz que nos dan en el problema.
      # Matriz Tridiagonal.
def construir_matriz_tridiagonal(n):
    A = np.zeros((n, n))
    A[0, 0] = 9
    A[0, 1] = -4
    A[0, 2] = 1
    for i in range(1, n - 1):
        A[i, i - 1] = -4
        A[i, i] = 6
        A[i, i + 1] = -4
        if i + 2 < n:
            A[i, i + 2] = 1
    A[n - 1, n - 3] = 1
    A[n - 1, n - 2] = -2
    A[n - 1, n - 1] = 1
    return A

    # Por bandas.
def SolveTipoBanda(A, b):
    n = A.shape[0]
    L = np.eye(n)
    U = np.copy(A)

    for i in range(n - 1):
        for j in range(i + 1, min(n, i + 4)):
            mult = U[j, i] / U[i, i]
            U[j, i:] -= mult * U[i, i:]
            L[j, i] = mult

    y = SustDelante(L, b)
    x = SustAtras(U, y)
    return x

    # Factorización del tipo Cholesky.
def construir_R(n):
    R = np.zeros((n, n))
    R[0, 0] = 2
    R[0, 1] = -2
    R[0, 2] = 1
    for i in range(1, n - 1):
        R[i, i - 1] = 1
        R[i, i] = -2
        R[i, i + 1] = 1
    R[n - 1, n - 2] = 1
    R[n - 1, n - 1] = -2
    return R

def SolveRRT(R, b):
    y = SustDelante(R, b)
    x = SustAtras(R.T, y)
    return x

  # Defino las dos matrices como se dio el problema.
  # Definimos para n=100 y n=1000
def resolver_y_comparar(n):
    print(f"\n--- Resultados para n = {n} ---\n")

    A = construir_matriz_tridiagonal(n)
    b = np.ones(n)

    # (a) LU normal
    x_LU = SolveLU(A, b)

    # (b) Tipo banda
    x_banda = SolveTipoBanda(A, b)

    # (c) A = R R.T
    R = construir_R(n)
    A_RRT = R @ R.T
    x_RRT = SolveRRT(R, b)

    # Solución analítica
    x_exacta = LA.solve(A, b)

# Aquí voy a imprimir los resultados para poder comparar.
    # Mostrar algunas entradas para comparar
    print("Primeros 5 valores con LU:")
    print(x_LU[:5])
    print("Primeros 5 valores con banda:")
    print(x_banda[:5])
    print("Primeros 5 valores con R*R.T:")
    print(x_RRT[:5])
    print("Primeros 5 valores con LA.solve:")
    print(x_exacta[:5])

    # Comparar errores
    print("\nErrores relativos:")
    print("LU:", LA.norm(x_LU - x_exacta) / LA.norm(x_exacta))
    print("Banda:", LA.norm(x_banda - x_exacta) / LA.norm(x_exacta))
    print("R*R.T:", LA.norm(x_RRT - x_exacta) / LA.norm(x_exacta))

# Ejecutar para n = 100 y n = 1000
resolver_y_comparar(100)
resolver_y_comparar(1000)




--- Resultados para n = 100 ---

Primeros 5 valores con LU:
[ 0.16666667 -0.41666667 -2.16666667 -4.5        -5.66666667]
Primeros 5 valores con banda:
[ 0.16666667 -0.41666667 -2.16666667 -4.5        -5.66666667]
Primeros 5 valores con R*R.T:
[0.     0.5    0.75   0.875  0.9375]
Primeros 5 valores con LA.solve:
[ 0.16666667 -0.41666667 -2.16666667 -4.5        -5.66666667]

Errores relativos:
LU: 9.149947213456228e-16
Banda: 9.149947213456228e-16
R*R.T: 0.9999999999999986

--- Resultados para n = 1000 ---

Primeros 5 valores con LU:
[ 0.16666667 -0.41666667 -2.16666667 -4.5        -5.66666667]
Primeros 5 valores con banda:
[ 0.16666667 -0.41666667 -2.16666667 -4.5        -5.66666667]
Primeros 5 valores con R*R.T:
[0.     0.5    0.75   0.875  0.9375]
Primeros 5 valores con LA.solve:
[ 0.16666667 -0.41666667 -2.16666667 -4.5        -5.66666667]

Errores relativos:
LU: 9.587059478393043e-14
Banda: 9.587059478393043e-14
R*R.T: 1.0
